%include "SIMDx86asm.inc"

EXPORT_SYMBOL(SIMDx86_sqrtf)
EXPORT_SYMBOL(SIMDx86_rsqrtf)
EXPORT_SYMBOL(SIMDx86_sqrt)
EXPORT_SYMBOL(SIMDx86_rsqrt)

BEGIN_SYMBOL(SIMDx86_sqrtf)
	resb	128
END_SYMBOL(SIMDx86_sqrtf)

BEGIN_SYMBOL(SIMDx86_rsqrtf)
END_SYMBOL(SIMDx86_rsqrtf)

BEGIN_SYMBOL(SIMDx86_sqrt)
END_SYMBOL(SIMDx86_sqrt)

BEGIN_SYMBOL(SIMDx86_rsqrt)
END_SYMBOL(SIMDx86_rsqrt)